### ISSUE TITLE
Cannot run on Mac Mojave

### ISSUE THREAD

**Issue by chernhaw** [mcauser/micropython-ssd1327#5]
I can't your helloworld  on Thonny after copying ssd1327.py to my rasppi pico, I got this error 

%Run -c $EDITOR_CONTENT
Traceback (most recent call last):
  File "<stdin>", line 13, in <module>
  File "ssd1327.py", line 191, in __init__
  File "ssd1327.py", line 178, in __init__
  File "ssd1327.py", line 77, in __init__
  File "ssd1327.py", line 121, in poweron
  File "ssd1327.py", line 182, in write_cmd
OSError: 5

**Comment by mcauser** [comment]
Usually caused by missing pull-ups on the I2C SDA/SCL pins.
Others have reported issues with SoftI2C/HW I2C on the pico.
I'll do some testing and make sure it works reliably.
